spring:
  application:
    name: TrafficInspection
  datasource:
    url: jdbc:postgresql://localhost:5432/TrafficInspectionDB
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
server:
  port: 8081