spring:
  application:
    name: TrafficInspection
  datasource:
    url: jdbc:postgresql://localhost:5432/TrafficInspectionDB
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: none # Чтобы хибернейт не трогал структуру БД
  liquibase:
    enabled: true # Liquibase занимается структурой БД
server:
  port: 8081