server:
  port: 8081
spring:
  application:
    name: TrafficInspectionApp
  datasource:
#    url: jdbc:postgresql://localhost:15432/traffic_inspection_db
    url: jdbc:postgresql://postgres/traffic_inspection_db
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    locations: classpath:db/migration